ALL_PERMISSIONS = [
    # ULB page and its buttons
    ('MENU_CREATE_ULB', 'Menu: Create ULB'),
    ('MENU_OPEN_ULB', 'Menu: Open ULB'),
    ('MENU_VIEW_ULB', 'Menu: View ULB'),
    ('BTN_EDIT_ULB', 'Button: Edit/Save ULB'),
    ('BTN_DELETE_ULB', 'Button: Delete ULB'),
    ('BTN_USER', 'Button: USER'),

    # Manage users and its buttons
    ('MENU_CREATE_USERS', 'Menu: Create Users'),
    ('MENU_MANAGE_USERS', 'Menu: Manage Users'),
    ('BTN_EDIT_USER', 'Button: Edit/Save User'),
    ('BTN_DELETE_USER', 'Button: Delete User'),
    ('BTN_TOGGLE_ACTIVE_USER', 'Button: Activate/Disable User'),
    ('MENU_MANAGE_ACCESS', 'Menu: Manage Access'),
    ('BTN_SEARCH_ACCESS', 'Button: Search Access'),
    ('BTN_SAVE_PERMISSIONS_ACCESS', 'Button: Save Permissions'),
    ('MENU_ULB_WISE_REPORT', 'Menu: ULB Wise Report'),
    ('MENU_USER_WISE_REPORT', 'Menu: User Wise Report'),
    ('MENU_ACCOUNTS_DASHBOARD', 'Menu: Accounts Dashboard'),

    ('MENU_ACCOUNTS_MASTER', 'Menu: Master'),  
    ('MENU_ACCOUNTS_MASTER_CREATE', 'Menu: Create: Ledger & Group'),
    ('MENU_ACCOUNTS_MASTER_VIEW_EDIT', 'Menu: View & Edit: Ledger & Group'),
    ('MENU_ACCOUNTS_MASTER_EXPORT', 'Menu: Accounts Master Export'),
    ('MENU_ACCOUNTS_MASTER_IMPORT', 'Menu: Accounts Master Import'),
    ('MENU_ACCOUNTS_TRANSACTION_ENTRY', 'Menu: Accounts Transaction Entry'),
    ('MENU_ACCOUNTS_TRIAL_BALANCE', 'Menu: Accounts Trial Balance'),
    ('MENU_ACCOUNTS_TRIAL_BALANCE_EXPORT_EXCEL', 'Menu: Accounts Trial Balance Export Excel'),
    ('MENU_ACCOUNTS_INCOME_EXPENDITURE', 'Menu: Accounts Income & Expenditure'),
    ('MENU_ACCOUNTS_BALANCE_SHEET', 'Menu: Accounts Balance Sheet'),
    ('MENU_ACCOUNTS_DAY_BOOK', 'Menu: Accounts Day Book'),
    ('MENU_ACCOUNTS_TRANSACTION_ENTRY_EDIT', 'Menu: Accounts Transaction Edit'),
    ('MENU_ACCOUNTS_TRANSACTION_ENTRY_DELETE', 'Menu: Accounts Transaction Delete'),
    ('MENU_ACCOUNTS_TRANSACTION_ENTRY_DUPLICATE', 'Menu: Accounts Transaction Duplicate'),
    ('MENU_ACCOUNTS_CASH_BOOK', 'Menu: Accounts Cash Book'),
    ('MENU_ACCOUNTS_LEDGER', 'Menu: Accounts Ledger'),
    ('MENU_ACCOUNTS_GST_REPORT', 'Menu: Accounts GST Report'),
    ('MENU_ACCOUNTS_TDS_REPORT', 'Menu: Accounts TDS Report'),
    ('MENU_ACCOUNTS_BRS', 'Menu: Accounts BRS'),
    ('MENU_ACCOUNTS_BRS_BANK_ENTRY', 'Menu: Accounts Bank Entry'),
    ('MENU_ACCOUNTS_BRS_SHOW_BANK_ENTRY', 'Menu: Accounts BRS Show Bank Entry'),
    ('BTN_ACCOUNTS_BRS_SHOW_BANK_ENTRY_EDIT', 'Button: BRS Show Bank Entry Edit'),
    ('BTN_ACCOUNTS_BRS_SHOW_BANK_ENTRY_DELETE', 'Button: BRS Show Bank Entry Delete'),
    ('MENU_ACCOUNTS_BRS_ADJUSTMENT', 'Menu: Accounts BRS Adjustment'),
    ('MENU_ACCOUNTS_SHOW_BRS_ADJUSTMENT', 'Menu: Accounts Show BRS Adjustment'),
    ('BTN_ACCOUNTS_BRS_ADJUSTMENT_EDIT', 'Button: BRS Adjustment Edit'),
    ('BTN_ACCOUNTS_BRS_ADJUSTMENT_UNDO', 'Button: BRS Adjustment Undo'),
    ('MENU_ACCOUNTS_BRS_STATEMENT', 'Menu: Accounts BRS Statement'),
    ('BTN_ACCOUNTS_BRS_STATEMENT_EDIT', 'Button: BRS Statement Edit'),
    ('BTN_ACCOUNTS_BRS_STATEMENT_PDF', 'Button: BRS Statement PDF'),
    ('MENU_ACCOUNTS_REPORT', 'Menu: Accounts Report'),
    # Reports - 15th Finance Commission
    ('MENU_REPORTS_15TH_FINANCE_COMMISSION', 'Menu: 15th Finance Commission'),
    ('MENU_15TH_FINANCE_COMMISSION_DEFINE', 'Menu: 15th Finance Commission Define'),
    ('BTN_15TH_FC_DEFINE_LEDGER', 'Button: Define Ledger'),
    ('BTN_15TH_FC_UNDO_LEDGER', 'Button: Undo Ledger'),
    ('MENU_15TH_FINANCE_COMMISSION_TRANSACTION_DEFINE', 'Menu: 15th Finance Commission Transaction Define'),
    ('BTN_15TH_FC_TRANSACTION_SAVE', 'Button: Save 15th Finance Transaction'),
    ('BTN_15TH_FC_TRANSACTION_EDIT', 'Button: Edit 15th Finance Transaction'),
    ('MENU_15TH_FINANCE_COMMISSION_REPORT', 'Menu: 15th Finance Commission Report'),
    # Reports - 6th Finance Commission
    ('MENU_REPORTS_6TH_FINANCE_COMMISSION', 'Menu: 6th Finance Commission'),
    ('MENU_6TH_FINANCE_COMMISSION_DEFINE', 'Menu: 6th Finance Commission Define'),
    ('BTN_6TH_FC_DEFINE_LEDGER', 'Button: Define Ledger'),
    ('BTN_6TH_FC_UNDO_LEDGER', 'Button: Undo Ledger'),
    ('MENU_6TH_FINANCE_COMMISSION_TRANSACTION_DEFINE', 'Menu: 6th Finance Commission Transaction Define'),
    ('BTN_6TH_FC_TRANSACTION_SAVE', 'Button: Save 6th Finance Transaction'),
    ('BTN_6TH_FC_TRANSACTION_EDIT', 'Button: Edit 6th Finance Transaction'),
    ('MENU_6TH_FINANCE_COMMISSION_REPORT', 'Menu: 6th Finance Commission Report'),
    # Utilization Certificate
    ('MENU_REPORTS_UTILIZATION_CERTIFICATE', 'Menu: Utilization Certificate(UC)'),
    ('MENU_UC_PREPARED', 'Menu: UC Prepared'),
    ('MENU_UC_REPORTS', 'Menu: UC Reports'),
    ('BTN_UC_OPEN_LAST', 'Button: Open Last UC'),
    ('BTN_UC_EXPORT_EXCEL', 'Button: Export Excel UC Report'),
    ('BTN_UC_OPEN_FORMS', 'Button: Open BTC Forms 42A AND ANNEXURES'),
]
