# Generated by Django 6.0.1 on 2026-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulb_name', models.CharField(max_length=255)),
                ('ulb_type', models.CharField(choices=[('NAGAR_NIGAM', 'Nagar Nigam'), ('NAGAR_PARISHAD', 'Nagar Parishad'), ('NAGAR_PANCHAYAT', 'Nagar Panchayat')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_no', models.CharField(max_length=20)),
                ('gst_no', models.CharField(max_length=20)),
                ('land_mark', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
