# Generated by Django 6.0.1 on 2026-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ulb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulb',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
