# Generated by Django 6.0.1 on 2026-01-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='ulb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.ulb'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'ulb', 'code')},
        ),
    ]
