# Generated by Django 6.0.1 on 2026-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_group_maingroup_subgroup_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulb',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='2026-01-25'),
            preserve_default=False,
        ),
    ]
