# Generated by Django 6.0.1 on 2026-01-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ulb_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group1',
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='children',
                    to='accounts.ledgergroup',
                )),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),

        # NEW: clear old group FK so it does not violate new constraint
        migrations.RunSQL(
            sql="UPDATE accounts_ledger SET group_id = NULL;",
            reverse_sql="UPDATE accounts_ledger SET group_id = NULL;",
        ),

        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ledgers',
                to='accounts.ledgergroup',
            ),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
