# Generated by Django 6.0.1 on 2026-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_ledger_group2_remove_ledger_group1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulb',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used in voucher numbers, e.g. DNP, SNN.', max_length=10, null=True, unique=True),
        ),
    ]
