# Generated by Django 6.0.1 on 2026-01-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ulb_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('RECEIPT', 'Receipts'), ('PAYMENT', 'Payments'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal')], max_length=10)),
                ('voucher_date', models.DateField()),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('sequence_no', models.IntegerField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ulb')),
            ],
            options={
                'ordering': ['-voucher_date', 'voucher_no'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptUCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_applicable', models.BooleanField(default=False)),
                ('major_head', models.CharField(blank=True, max_length=100)),
                ('treasury_code', models.CharField(blank=True, max_length=50)),
                ('uc_bill_no', models.CharField(blank=True, max_length=100)),
                ('uc_bill_date', models.DateField(blank=True, null=True)),
                ('sub_major_head', models.CharField(blank=True, max_length=100)),
                ('ddo_code', models.CharField(blank=True, max_length=50)),
                ('letter_no', models.CharField(blank=True, max_length=100)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('minor_head', models.CharField(blank=True, max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('tv_no', models.CharField(blank=True, max_length=100)),
                ('tv_date', models.DateField(blank=True, null=True)),
                ('sub_head', models.CharField(blank=True, max_length=100)),
                ('bill_code', models.CharField(blank=True, max_length=50)),
                ('transaction', models.OneToOneField(limit_choices_to={'voucher_type': 'RECEIPT'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('gst_type', models.CharField(blank=True, choices=[('inter', 'Inter State'), ('intra', 'Intra State')], max_length=10)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_pan_no', models.CharField(blank=True, max_length=20)),
                ('tds_section', models.CharField(blank=True, max_length=10)),
                ('tds_nature', models.CharField(blank=True, max_length=50)),
                ('tds_type', models.CharField(blank=True, max_length=20)),
                ('tds_rate', models.CharField(blank=True, max_length=10)),
                ('transaction', models.OneToOneField(limit_choices_to={'voucher_type': 'PAYMENT'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Dr', 'Dr'), ('Cr', 'Cr')], max_length=2)),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
