# Generated by Django 6.0.1 on 2026-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_transaction_receiptucdetails_paymentvendordetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvendordetails',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptucdetails',
            name='grant_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
