# Generated by Django 6.0.1 on 2026-02-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_paymentvendordetails_tds_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='head_group_code',
            field=models.IntegerField(blank=True, choices=[(1, '1 Income'), (2, '2 Expenses'), (3, '3 Liabilities'), (4, '4 Assets')], help_text='1 Income, 2 Expenses, 3 Liabilities, 4 Assets', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_type',
            field=models.CharField(choices=[('RECV', 'Receipts'), ('PYMT', 'Payments'), ('CNTR', 'Contra'), ('JRNL', 'Journal')], max_length=10),
        ),
        migrations.CreateModel(
            name='BankReconciliationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=2)),
                ('entry_date', models.DateField()),
                ('bank_narration', models.CharField(blank=True, max_length=255)),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, help_text='Use when Type = Dr.', max_digits=15)),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, help_text='Use when Type = Cr.', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brs_entries', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(help_text='Bank ledger (usually starting with 450...).', on_delete=django.db.models.deletion.CASCADE, related_name='brs_entries', to='accounts.ledger')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brs_entries', to='accounts.ulb')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
