# Generated by Django 6.0.1 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_ledger_head_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliationentry',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
