# Generated by Django 6.0.1 on 2026-02-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_bankreconciliationentry_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionentry',
            name='is_brs_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
