# Generated by Django 6.0.1 on 2026-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_transactionentry_is_brs_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliationentry',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
