# Generated by Django 6.0.1 on 2026-02-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_bankreconciliationentry_is_reconciled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliationentry',
            name='bank_narration',
            field=models.TextField(blank=True),
        ),
    ]
