# Generated by Django 6.0.1 on 2026-02-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_bankreconciliationentry_bank_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliationentry',
            name='brs_adjustment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionentry',
            name='brs_adjustment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
