# Generated by Django 6.0.1 on 2026-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_bankreconciliationentry_brs_adjustment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliationentry',
            name='particulars',
            field=models.TextField(blank=True),
        ),
    ]
