# Generated by Django 6.0.1 on 2026-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bankreconciliationentry_particulars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankreconciliationentry',
            old_name='particulars',
            new_name='brs_bank_particulars',
        ),
        migrations.AddField(
            model_name='transactionentry',
            name='brs_cash_particulars',
            field=models.TextField(blank=True),
        ),
    ]
