# Generated by Django 6.0.1 on 2026-03-01 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_particulars_bankreconciliationentry_brs_bank_particulars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifteenthFinanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_on', models.DateTimeField(auto_now_add=True)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifteenth_finance_defined_ledgers', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifteenth_finance_mappings', to='accounts.ledger')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifteenth_finance_ledgers', to='accounts.ulb')),
            ],
            options={
                'verbose_name': '15th Finance Ledger',
                'verbose_name_plural': '15th Finance Ledgers',
                'unique_together': {('ulb', 'ledger')},
            },
        ),
    ]
