# Generated by Django 6.0.1 on 2026-03-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_fifteenthfinanceledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fifteenthfinanceledger',
            options={},
        ),
        migrations.RenameField(
            model_name='fifteenthfinanceledger',
            old_name='defined_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='amount_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='amount_rhwr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='amount_swm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='amount_untied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fifteenthfinanceledger',
            name='defined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fifteenthfinanceledger',
            name='ulb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifteenth_finance_mappings', to='accounts.ulb'),
        ),
    ]
