# Generated by Django 6.0.1 on 2026-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_fifteenthfinanceledger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='as_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
