# Generated by Django 6.0.1 on 2026-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_fifteenthfinanceledger_as_on_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='last_ratio_type',
            field=models.CharField(blank=True, help_text='Last used 15th FC ratio type for this ledger (40 / 30_swm / 30_rhwr / interest).', max_length=20, null=True),
        ),
    ]
