# Generated by Django 6.0.1 on 2026-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_fifteenthfinanceledger_last_ratio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifteenthfinanceledger',
            name='ratio_locked',
            field=models.BooleanField(default=False, help_text='If true, ratio select is locked in transaction view until user clicks Edit.'),
        ),
    ]
