# Generated by Django 6.0.1 on 2026-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_fifteenthfinanceledger_ratio_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifteenthfinanceledger',
            name='last_ratio_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
