# Generated by Django 6.0.1 on 2026-03-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_fifteenthfinanceledger_last_ratio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifteenthFinanceTxnRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_type', models.CharField(choices=[('40', '40% - Untied'), ('30_swm', '30% - SWM'), ('30_rhwr', '30% - RHWR'), ('interest', 'Interest')], max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ulb')),
            ],
            options={
                'unique_together': {('ulb', 'transaction', 'ledger')},
            },
        ),
    ]
