# Generated by Django 6.0.1 on 2026-03-12 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_fifteenthfinancetxnratio_ratio_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixthFinanceTxnAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_type', models.CharField(choices=[('DEV_TOTAL', 'Development Fund (30%)'), ('MAINT', 'Maintenance Fund (20%)'), ('GENERAL', 'General Fund (50%)'), ('DEV_TIED_TOTAL', 'Development Tied Fund (60% of Dev)'), ('DEV_TIED_SWM', 'Development Tied - SWM (44% of Tied)'), ('DEV_TIED_OTHERS', 'Development Tied - Others (16% of Tied)'), ('DEV_UNTIED', 'Development Untied Fund (40% of Dev)')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ulb')),
            ],
        ),
        migrations.CreateModel(
            name='SixthFinanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_dev_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_dev_tied_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_dev_tied_swm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_dev_tied_others', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_dev_untied', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_maint', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_general', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_ratio_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ratio_locked', models.BooleanField(default=False, help_text='If true, ratio select is locked in transaction view until user clicks Edit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_finance_mappings', to='accounts.ledger')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_finance_mappings', to='accounts.ulb')),
            ],
            options={
                'unique_together': {('ulb', 'ledger')},
            },
        ),
        migrations.CreateModel(
            name='SixthFinanceTxnRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
                ('ulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ulb')),
            ],
            options={
                'unique_together': {('ulb', 'transaction', 'ledger')},
            },
        ),
    ]
