# Generated by Django 6.0.1 on 2026-03-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_sixthfinancetxnallocation_sixthfinanceledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUCUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('payment_txn', models.OneToOneField(limit_choices_to={'voucher_type': 'PYMT'}, on_delete=django.db.models.deletion.CASCADE, related_name='uc_usage', to='accounts.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptUCUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('receipt_uc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilization', to='accounts.receiptucdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptUCUtilizationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_on', models.DateField()),
                ('uc_identifier', models.CharField(max_length=50)),
                ('payment_txn', models.ForeignKey(limit_choices_to={'voucher_type': 'PYMT'}, on_delete=django.db.models.deletion.PROTECT, to='accounts.transaction')),
                ('receipt_uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_lines', to='accounts.receiptucdetails')),
            ],
        ),
    ]
