# Generated by Django 6.0.1 on 2026-03-14 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_paymentucusage_receiptucutilization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptucutilization',
            name='uc_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
