# Generated by Django 6.0.1 on 2026-03-15 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_receiptucutilization_uc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptucutilizationline',
            name='receipt_uc',
        ),
        migrations.AddField(
            model_name='receiptucutilization',
            name='uc_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='receiptucutilizationline',
            name='utilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.receiptucutilization'),
        ),
        migrations.AlterField(
            model_name='receiptucutilization',
            name='receipt_uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='accounts.receiptucdetails'),
        ),
        migrations.AlterField(
            model_name='receiptucutilization',
            name='uc_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
